# Generated by Django 5.0.4 on 2025-06-23 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0002_productsize"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="productsize",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dressapp.sizeoption"
            ),
        ),
    ]
